[package]
name = "remote-package"
version = "0.1.0"
edition = "2021"
author = "Max Dymond <cmeister2@gmail.com>"

[dependencies]
debpkg = "0.5.0"
reqwest = { version = "0.11.10", features = ["blocking"] }
thiserror = "1.0.30"
