[package]
name = "remote-package"
version = "0.1.0"
edition = "2018"
authors = ["Max Dymond <cmeister2@gmail.com>"]
description = "A simple crate to query remote packages for information."
license = "MIT"
repository = "https://github.com/cmeister2/remote-package"

[dependencies]
debpkg = { version = "0.5.0", optional = true }
reqwest = { version = "0.11.10", features = ["blocking"], optional = true }
thiserror = "1.0.30"

[features]
default = ["http", "debian"]
http = ["reqwest"]
debian = ["debpkg"]