[package]
name = "remote-package"
version = "0.1.0"
edition = "2018"
author = "Max Dymond <cmeister2@gmail.com>"
description = "A simple crate to query remote packages for information."
license = "MIT"
repository = "https://github.com/cmeister2/remote-package"

[dependencies]
debpkg = "0.5.0"
reqwest = { version = "0.11.10", features = ["blocking"] }
thiserror = "1.0.30"
